services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true
    bind:
      $bundleConfig: '%huh_ldap%'

  HeimrichHannot\LdapBundle\:
    resource: '../../{Command,EventListener,Util}/*'
